<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Prediction Assignment Writeup</title>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: #990073
   }

   pre .number {
     color: #099;
   }

   pre .comment {
     color: #998;
     font-style: italic
   }

   pre .keyword {
     color: #900;
     font-weight: bold
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: #d14;
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>

<!-- MathJax scripts -->
<script type="text/javascript" src="https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>


<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}

pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<h2>Prediction Assignment Writeup</h2>

<p>The first step was to look at the data and clean the data.</p>

<p>Removed user name, time based columns and other factor columns.
Removed rows that were marked as new window = yes
Removed mean, variance, std deviation, max, min, etc that were used in the: <a href="http://groupware.les.inf.puc-rio.br/public/papers/2013.Velloso.QAR-WLE.pdf">original paper</a> for feature selection.</p>

<p>After observing the data it was very hard to determine pattern / correlation between predictors and classification due to number of predictors (52 after cleaning the data). </p>

<p>So approach I took was to selected as small sample for initial experiment about 5% of test data and run train function without specifying method. 
Best method was identified using &ldquo;random forest&rdquo; algorithm. Accuracy was at about 80%.</p>

<p>After that I&#39;ve selected larger data set of 20% for training set and left rest for testing:</p>

<pre><code class="r">library(caret)

# Please set path to the folder you have downloaded CSV files to. Please note original CSV files were modified to clean up data.
setwd(&quot;D:/Install/R&quot;)

data &lt;- read.csv(&quot;pml-training-no.csv&quot;)
set.seed(107)
inTraining &lt;- createDataPartition(data$classe, p = 0.2, list = FALSE)
training &lt;-data[inTraining,]
testing &lt;-data[-inTraining,]
rfFit &lt;- train(classe ~ ., data = training, method = &quot;rf&quot;)
rfFit
</code></pre>

<pre><code>## Random Forest 
## 
## 3846 samples
##   52 predictors
##    5 classes: &#39;A&#39;, &#39;B&#39;, &#39;C&#39;, &#39;D&#39;, &#39;E&#39; 
## 
## No pre-processing
## Resampling: Bootstrapped (25 reps) 
## 
## Summary of sample sizes: 3846, 3846, 3846, 3846, 3846, 3846, ... 
## 
## Resampling results across tuning parameters:
## 
##   mtry  Accuracy  Kappa  Accuracy SD  Kappa SD
##   2     1         0.9    0.005        0.007   
##   30    1         0.9    0.005        0.007   
##   50    0.9       0.9    0.009        0.01    
## 
## Accuracy was used to select the optimal model using  the largest value.
## The final value used for the model was mtry = 27.
</code></pre>

<pre><code class="r">rfFit$finalModel
</code></pre>

<pre><code>## 
## Call:
##  randomForest(x = x, y = y, mtry = param$mtry) 
##                Type of random forest: classification
##                      Number of trees: 500
## No. of variables tried at each split: 27
## 
##         OOB estimate of  error rate: 2.91%
## Confusion matrix:
##      A   B   C   D   E class.error
## A 1084   6   3   1   1     0.01005
## B   21 711   9   2   1     0.04435
## C    1  22 640   7   1     0.04620
## D    1   2  15 609   3     0.03333
## E    0   3   6   7 690     0.02266
</code></pre>

<p>Then I&#39;ve used model to run cross validation on the testing set:</p>

<pre><code class="r">rfClasses &lt;- predict(rfFit, newdata = testing)
</code></pre>

<p>Prediction on testing set (80% of test data) turned out to be quite good with Accuracy: 96% and OOB estimate of error rate of 2.91%</p>

<pre><code class="r">confusionMatrix(data = rfClasses, testing$classe)
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 4353  117    1    2    4
##          B   18 2799   95    9   35
##          C    0   49 2557   77    7
##          D    1    9   27 2425   27
##          E    4    0    1    4 2749
## 
## Overall Statistics
##                                         
##                Accuracy : 0.968         
##                  95% CI : (0.965, 0.971)
##     No Information Rate : 0.285         
##     P-Value [Acc &gt; NIR] : &lt;2e-16        
##                                         
##                   Kappa : 0.96          
##  Mcnemar&#39;s Test P-Value : &lt;2e-16        
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             0.995    0.941    0.954    0.963    0.974
## Specificity             0.989    0.987    0.990    0.995    0.999
## Pos Pred Value          0.972    0.947    0.951    0.974    0.997
## Neg Pred Value          0.998    0.986    0.990    0.993    0.994
## Prevalence              0.285    0.193    0.174    0.164    0.184
## Detection Rate          0.283    0.182    0.166    0.158    0.179
## Detection Prevalence    0.291    0.192    0.175    0.162    0.179
## Balanced Accuracy       0.992    0.964    0.972    0.979    0.987
</code></pre>

<p>Next I&#39;ve produced results for the validation data set:</p>

<pre><code class="r">validateData &lt;- read.csv(&quot;pml-testing.csv&quot;)
answers &lt;- predict(rfFit, newdata = validateData)
answers
</code></pre>

<pre><code>##  [1] B A B A A E D B A A B C B A E E A B B B
## Levels: A B C D E
</code></pre>

<p>Submission of test cases confirmed 20/20 match on validation set that match well estimated model accuracy on the training/test set.</p>

<p>Although results were positive (achieved high accuracy) the downside of RandomForest is the fitted model is not human-readable.
It was hard to plot graphs or interpret outcome due to nature of the Forest tree algorithm. One of the ways to interpret model was to show importance of predictors to make some sense of the resulting model:</p>

<pre><code class="r">importance(rfFit$finalModel)
</code></pre>

<pre><code>##                      MeanDecreaseGini
## roll_belt                      375.48
## pitch_belt                     155.18
## yaw_belt                       197.94
## total_accel_belt                15.96
## gyros_belt_x                    15.46
## gyros_belt_y                    11.40
## gyros_belt_z                    38.55
## accel_belt_x                    13.95
## accel_belt_y                    13.81
## accel_belt_z                    59.14
## magnet_belt_x                   51.15
## magnet_belt_y                   71.51
## magnet_belt_z                   69.10
## roll_arm                        33.06
## pitch_arm                       19.94
## yaw_arm                         50.40
## total_accel_arm                 16.30
## gyros_arm_x                     18.80
## gyros_arm_y                     24.83
## gyros_arm_z                     11.08
## accel_arm_x                     28.93
## accel_arm_y                     23.32
## accel_arm_z                     15.24
## magnet_arm_x                    34.88
## magnet_arm_y                    32.67
## magnet_arm_z                    23.59
## roll_dumbbell                   87.32
## pitch_dumbbell                  23.67
## yaw_dumbbell                    45.36
## total_accel_dumbbell            62.33
## gyros_dumbbell_x                21.21
## gyros_dumbbell_y                36.48
## gyros_dumbbell_z                13.53
## accel_dumbbell_x                26.36
## accel_dumbbell_y                94.06
## accel_dumbbell_z                52.19
## magnet_dumbbell_x               69.71
## magnet_dumbbell_y              175.98
## magnet_dumbbell_z              168.24
## roll_forearm                   154.58
## pitch_forearm                  242.98
## yaw_forearm                     27.37
## total_accel_forearm             15.40
## gyros_forearm_x                 10.57
## gyros_forearm_y                 18.68
## gyros_forearm_z                 13.19
## accel_forearm_x                 83.71
## accel_forearm_y                 20.79
## accel_forearm_z                 40.73
## magnet_forearm_x                30.53
## magnet_forearm_y                32.93
## magnet_forearm_z                49.83
</code></pre>

<p>In order to improve on readability of the model an attempt was made to use rpart method of library(rpart) that produced single classification tree potentially readable. The results were not promising with cross validation accuracy of 30% that was fairly low compare to Random forest result.</p>

<p>Another attempt was made to use &ldquo;party&rdquo; library and ctree algorithm that as well output single classification tree:</p>

<pre><code class="r">inTraining &lt;- createDataPartition(data$classe, p = 0.5, list = FALSE)
training &lt;-data[inTraining,]
testing &lt;-data[-inTraining,]
ctFit &lt;- ctree(classe ~ ., data = training)
ctFit
</code></pre>

<pre><code>## 
##   Conditional inference tree with 317 terminal nodes
## 
## Response:  classe 
## Inputs:  roll_belt, pitch_belt, yaw_belt, total_accel_belt, gyros_belt_x, gyros_belt_y, gyros_belt_z, accel_belt_x, accel_belt_y, accel_belt_z, magnet_belt_x, magnet_belt_y, magnet_belt_z, roll_arm, pitch_arm, yaw_arm, total_accel_arm, gyros_arm_x, gyros_arm_y, gyros_arm_z, accel_arm_x, accel_arm_y, accel_arm_z, magnet_arm_x, magnet_arm_y, magnet_arm_z, roll_dumbbell, pitch_dumbbell, yaw_dumbbell, total_accel_dumbbell, gyros_dumbbell_x, gyros_dumbbell_y, gyros_dumbbell_z, accel_dumbbell_x, accel_dumbbell_y, accel_dumbbell_z, magnet_dumbbell_x, magnet_dumbbell_y, magnet_dumbbell_z, roll_forearm, pitch_forearm, yaw_forearm, total_accel_forearm, gyros_forearm_x, gyros_forearm_y, gyros_forearm_z, accel_forearm_x, accel_forearm_y, accel_forearm_z, magnet_forearm_x, magnet_forearm_y, magnet_forearm_z 
## Number of observations:  9609 
## 
## 1) pitch_forearm &lt;= -33.7; criterion = 1, statistic = 1883.33
##   2) gyros_dumbbell_y &lt;= 0.51; criterion = 1, statistic = 64.094
##     3) gyros_arm_y &lt;= -0.82; criterion = 1, statistic = 53.774
##       4)*  weights = 22 
##     3) gyros_arm_y &gt; -0.82
##       5)*  weights = 790 
##   2) gyros_dumbbell_y &gt; 0.51
##     6)*  weights = 10 
## 1) pitch_forearm &gt; -33.7
##   7) magnet_belt_y &lt;= 557; criterion = 1, statistic = 1004.72
##     8) magnet_dumbbell_z &lt;= 146; criterion = 1, statistic = 431.513
##       9) magnet_forearm_z &lt;= -332; criterion = 1, statistic = 96.196
##         10)*  weights = 9 
##       9) magnet_forearm_z &gt; -332
##         11) gyros_dumbbell_x &lt;= 1.14; criterion = 0.997, statistic = 19.633
##           12)*  weights = 530 
##         11) gyros_dumbbell_x &gt; 1.14
##           13)*  weights = 7 
##     8) magnet_dumbbell_z &gt; 146
##       14) magnet_belt_z &lt;= -434; criterion = 1, statistic = 112.643
##         15) yaw_belt &lt;= -87.5; criterion = 1, statistic = 57.344
##           16)*  weights = 13 
##         15) yaw_belt &gt; -87.5
##           17)*  weights = 118 
##       14) magnet_belt_z &gt; -434
##         18)*  weights = 34 
##   7) magnet_belt_y &gt; 557
##     19) roll_dumbbell &lt;= -95.5; criterion = 1, statistic = 831.254
##       20) magnet_belt_x &lt;= 46; criterion = 1, statistic = 194.92
##         21) gyros_belt_z &lt;= 0.11; criterion = 1, statistic = 203.944
##           22) total_accel_forearm &lt;= 6; criterion = 1, statistic = 140.876
##             23) gyros_arm_x &lt;= 0.22; criterion = 1, statistic = 32.636
##               24)*  weights = 9 
##             23) gyros_arm_x &gt; 0.22
##               25)*  weights = 26 
...
...
fragment was removed manually to reduce the size and for readability
...
...
##                   623) pitch_forearm &gt; -1.77
##                     627) magnet_belt_z &lt;= -308; criterion = 1, statistic = 23.525
##                       628)*  weights = 77 
##                     627) magnet_belt_z &gt; -308
##                       629) roll_belt &lt;= -0.03; criterion = 0.997, statistic = 19.236
##                         630)*  weights = 27 
##                       629) roll_belt &gt; -0.03
##                         631) magnet_dumbbell_z &lt;= 117; criterion = 0.996, statistic = 19.079
##                           632)*  weights = 22 
##                         631) magnet_dumbbell_z &gt; 117
##                           633)*  weights = 19
</code></pre>

<p>Model consisted of 317 nodes and 633 level depth and was not easily interpretable. </p>

<p>After fitting model and cross validating on the training set result produced was fairly good with accuracy of 85%.</p>

<pre><code class="r">ctClass &lt;- predict(ctFit, newdata = testing)
confusionMatrix(ctClass, testing$classe)
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 2505  117   32   47   35
##          B  112 1576  126   66   81
##          C   40   78 1360  133   76
##          D   52   43   99 1272   52
##          E   26   45   59   55 1520
## 
## Overall Statistics
##                                        
##                Accuracy : 0.857        
##                  95% CI : (0.85, 0.864)
##     No Information Rate : 0.285        
##     P-Value [Acc &gt; NIR] : &lt; 2e-16      
##                                        
##                   Kappa : 0.819        
##  Mcnemar&#39;s Test P-Value : 7.72e-05     
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             0.916    0.848    0.811    0.809    0.862
## Specificity             0.966    0.950    0.959    0.969    0.976
## Pos Pred Value          0.916    0.804    0.806    0.838    0.891
## Neg Pred Value          0.967    0.963    0.960    0.963    0.969
## Prevalence              0.285    0.194    0.174    0.164    0.184
## Detection Rate          0.261    0.164    0.142    0.132    0.158
## Detection Prevalence    0.285    0.204    0.176    0.158    0.177
## Balanced Accuracy       0.941    0.899    0.885    0.889    0.919
</code></pre>

<p>In conclusion rpart and ctree methods accuracy was lower and there was no improvement in readability of the model. Random Forest model still offered optimal accuracy compared to other models.</p>

</body>

</html>
